In [1]:
import pandas as pd
import numpy as np
import random

random.seed(0)
np.random.seed(0)

# Load MovieLens 1M ratings
ratings_df = pd.read_csv(
    "../dataset/ratings.dat",
    sep="::",
    engine="python",  # needed because the separator is multi-character
    encoding="latin-1",  # needed due to accented characters
    names=["userId", "movieId", "rating", "timestamp"],
)

# Load MovieLens 1M movies (for later CBF)
movies_df = pd.read_csv(
    "../dataset/movies.dat",
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["movieId", "title", "genres"],
)

print(ratings_df.head())
print(movies_df.head())
print("Full ratings shape:", ratings_df.shape)

   userId  movieId  rating  timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291
   movieId                               title                        genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy
Full ratings shape: (1000209, 4)

In [2]:
from collections import Counter
import numpy as np

# Count ratings per user on the FULL ratings_df (before sampling)
user_counts = ratings_df["userId"].value_counts()

DENSE_THRESHOLD = 100  # or whatever you used later


def user_weight(u):
    c = user_counts[u]
    base = np.log1p(c)  # keep your original shape
    # Boost dense users
    if c >= DENSE_THRESHOLD:
        return base * 100  # 20x more likely than sparse users
    else:
        return base


weights = ratings_df["userId"].map(user_weight)

ratings_sample = ratings_df.sample(
    n=100_000,
    weights=weights,
    random_state=0,
).reset_index(drop=True)

In [3]:
ratings_sample["userId"].nunique()

3067

In [4]:
from collections import Counter

user_counts_sample = Counter(ratings_sample["userId"])

print("Users with <5 ratings:", sum(1 for u, c in user_counts_sample.items() if c < 5))
print(
    "Users with 5-20 ratings:",
    sum(1 for u, c in user_counts_sample.items() if 5 <= c <= 20),
)
print(
    "Users with >20 ratings:", sum(1 for u, c in user_counts_sample.items() if c > 20)
)
print("Max ratings by a user:", max(user_counts_sample.values()))
print(
    "Mean ratings per user:", sum(user_counts_sample.values()) / len(user_counts_sample)
)

Users with <5 ratings: 131
Users with 5-20 ratings: 1280
Users with >20 ratings: 1656
Max ratings by a user: 371
Mean ratings per user: 32.605151613955

In [5]:
from collections import Counter

# Count how many ratings each item received in the sampled dataset
item_counts_sample = Counter(ratings_sample["movieId"])

print(
    "Items with <5 ratings:", sum(1 for item, c in item_counts_sample.items() if c < 5)
)

print(
    "Items with 5-20 ratings:",
    sum(1 for item, c in item_counts_sample.items() if 5 <= c <= 20),
)

print(
    "Items with >20 ratings:",
    sum(1 for item, c in item_counts_sample.items() if c > 20),
)

print("Max ratings for an item:", max(item_counts_sample.values()))

print(
    "Mean ratings per item:", sum(item_counts_sample.values()) / len(item_counts_sample)
)

Items with <5 ratings: 725
Items with 5-20 ratings: 1133
Items with >20 ratings: 1483
Max ratings for an item: 239
Mean ratings per item: 29.931158335827597

In [6]:
# Map user & item IDs to dense indices
user_map = {
    old_id: new_id for new_id, old_id in enumerate(ratings_sample["userId"].unique())
}
ratings_sample["user_idx"] = ratings_sample["userId"].map(user_map)

item_map = {
    old_id: new_id for new_id, old_id in enumerate(ratings_sample["movieId"].unique())
}
ratings_sample["item_idx"] = ratings_sample["movieId"].map(item_map)

reverse_item_map = {new: old for old, new in item_map.items()}

triplets = [
    (int(user), int(item), float(rating))
    for user, item, rating in zip(
        ratings_sample["user_idx"],
        ratings_sample["item_idx"],
        ratings_sample["rating"],
    )
]

triplets[:10]

[(0, 0, 5.0),
 (1, 1, 3.0),
 (2, 2, 4.0),
 (3, 3, 4.0),
 (4, 4, 1.0),
 (5, 5, 4.0),
 (6, 6, 4.0),
 (7, 7, 4.0),
 (8, 8, 5.0),
 (9, 9, 4.0)]

In [7]:
ratings_sample["user_idx"].value_counts().head()
# ratings_sample["user_idx"].value_counts().min(), ratings_sample["user_idx"].value_counts().max()

user_idx
41      371
455     263
735     249
1       235
1117    234
Name: count, dtype: int64

In [8]:
num_users = ratings_sample["userId"].nunique()
num_items = ratings_sample["movieId"].nunique()
num_interactions = len(ratings_sample)

density = num_interactions / (num_users * num_items)
sparsity = 1.0 - density

print(f"Users: {num_users}")
print(f"Items: {num_items}")
print(f"Interactions: {num_interactions}")
print(f"Density:  {density:.6f}")
print(f"Sparsity: {sparsity:.6f}")

Users: 3067
Items: 3341
Interactions: 100000
Density:  0.009759
Sparsity: 0.990241

In [9]:
from collections import Counter
import random

# Count #ratings per user on the full 100K
user_counts_all = Counter(u for u, _, _ in triplets)

DENSE_THRESHOLD = 20

dense_users = {u for u, c in user_counts_all.items() if c >= DENSE_THRESHOLD}
cold_users = {u for u, c in user_counts_all.items() if c < DENSE_THRESHOLD}

print("Total users:", len(user_counts_all))
print("Dense users (>=20):", len(dense_users))
print("Cold users (<20):", len(cold_users))

# Split triplets into dense and cold groups
dense_triplets = [t for t in triplets if t[0] in dense_users]
cold_triplets = [t for t in triplets if t[0] in cold_users]

print("Dense triplets:", len(dense_triplets))
print("Cold triplets :", len(cold_triplets))

Total users: 3067
Dense users (>=20): 1726
Cold users (<20): 1341
Dense triplets: 84332
Cold triplets : 15668

In [10]:
dense_triplets_shuffled = dense_triplets.copy()
random.shuffle(dense_triplets_shuffled)

n_dense = len(dense_triplets_shuffled)

train_end = int(0.6 * n_dense)
val_end = int(0.8 * n_dense)  # 60% train, 20% val, 20% test

train_dense_triplets = dense_triplets_shuffled[:train_end]
val_dense_triplets = dense_triplets_shuffled[train_end:val_end]
test_dense_triplets = dense_triplets_shuffled[val_end:]

print("Train (dense):", len(train_dense_triplets))
print("Val   (dense):", len(val_dense_triplets))
print("Test  (dense):", len(test_dense_triplets))

train_triplets = train_dense_triplets

Train (dense): 50599
Val   (dense): 16866
Test  (dense): 16867

In [11]:
num_users = ratings_sample["user_idx"].nunique()
num_items = ratings_sample["item_idx"].nunique()

num_factors = 20
learning_rate = 0.02
reg = 0.05
num_epochs = 20

# Global mean from dense TRAIN only
global_mean = np.mean([r for (_, _, r) in train_triplets])

user_bias = np.zeros(num_users, dtype=np.float32)
item_bias = np.zeros(num_items, dtype=np.float32)
user_factors = 0.1 * np.random.randn(num_users, num_factors).astype(np.float32)
item_factors = 0.1 * np.random.randn(num_items, num_factors).astype(np.float32)

print("Global mean (dense train):", global_mean)

Global mean (dense train): 3.5022431273345322

In [12]:
def svd_score(u, i):
    return (
        global_mean
        + user_bias[u]
        + item_bias[i]
        + np.dot(user_factors[u], item_factors[i])
    )


def rmse(triplets):
    se = 0.0
    for u, i, r in triplets:
        pred = svd_score(u, i)
        se += (r - pred) ** 2
    return np.sqrt(se / len(triplets))

In [13]:
def train_svd_sgd(train_triplets, val_triplets, num_epochs, learning_rate, reg):
    global user_bias, item_bias, user_factors, item_factors

    best_val_rmse = None

    for epoch in range(num_epochs):
        random.shuffle(train_triplets)

        squared_e_train = 0.0

        for u, i, r in train_triplets:
            # Current prediction
            pred = (
                global_mean
                + user_bias[u]
                + item_bias[i]
                + np.dot(user_factors[u], item_factors[i])
            )
            err = r - pred
            squared_e_train += err**2

            # Cache old factors so we don't use partially updated values
            pu = user_factors[u].copy()
            qi = item_factors[i].copy()

            # Update biases
            user_bias[u] += learning_rate * (err - reg * user_bias[u])
            item_bias[i] += learning_rate * (err - reg * item_bias[i])

            # Update latent factors
            user_factors[u] += learning_rate * (err * qi - reg * pu)
            item_factors[i] += learning_rate * (err * pu - reg * qi)

        train_rmse = np.sqrt(squared_e_train / len(train_triplets))
        val_rmse = rmse(val_triplets)

        if best_val_rmse is None or val_rmse < best_val_rmse:
            best_val_rmse = val_rmse

        print(
            f"Epoch {epoch+1}/{num_epochs} "
            f"- Train RMSE: {train_rmse} | Val RMSE: {val_rmse}"
        )

    print("Best validation RMSE:", best_val_rmse)
    return best_val_rmse

In [14]:
# after tuning

best_val = train_svd_sgd(
    train_triplets=train_triplets,
    val_triplets=val_dense_triplets,
    num_epochs=num_epochs,
    learning_rate=learning_rate,
    reg=reg,
)

Epoch 1/20 - Train RMSE: 1.0373035245611821 | Val RMSE: 0.991383471091583
Epoch 2/20 - Train RMSE: 0.941738762132222 | Val RMSE: 0.9623834358112495
Epoch 3/20 - Train RMSE: 0.9058076586973646 | Val RMSE: 0.9518656244926031
Epoch 4/20 - Train RMSE: 0.8851252446269469 | Val RMSE: 0.946773852863172
Epoch 5/20 - Train RMSE: 0.8696281588108592 | Val RMSE: 0.9440164997314436
Epoch 6/20 - Train RMSE: 0.8565675102939999 | Val RMSE: 0.9428051546006356
Epoch 7/20 - Train RMSE: 0.8439762387871729 | Val RMSE: 0.9420850378099744
Epoch 8/20 - Train RMSE: 0.8306140945421187 | Val RMSE: 0.9420190887883741
Epoch 9/20 - Train RMSE: 0.8160652965413977 | Val RMSE: 0.9418338519412041
Epoch 10/20 - Train RMSE: 0.7997255090736248 | Val RMSE: 0.942464313308004
Epoch 11/20 - Train RMSE: 0.7816080752778928 | Val RMSE: 0.9435356598828432
Epoch 12/20 - Train RMSE: 0.7612776240800339 | Val RMSE: 0.9444486793760479
Epoch 13/20 - Train RMSE: 0.7393409943693448 | Val RMSE: 0.9470294227322231
Epoch 14/20 - Train RMSE: 0.716133118328433 | Val RMSE: 0.9496393101502064
Epoch 15/20 - Train RMSE: 0.692135180371128 | Val RMSE: 0.9526915679167863
Epoch 16/20 - Train RMSE: 0.6678605987273206 | Val RMSE: 0.9563728422388563
Epoch 17/20 - Train RMSE: 0.643807391414517 | Val RMSE: 0.960553328645578
Epoch 18/20 - Train RMSE: 0.620538828075146 | Val RMSE: 0.9653922537646145
Epoch 19/20 - Train RMSE: 0.5980781980901926 | Val RMSE: 0.9693329279533468
Epoch 20/20 - Train RMSE: 0.576991107855295 | Val RMSE: 0.9741513086987547
Best validation RMSE: 0.9418338519412041

In [15]:
def test_svd_config(
    num_factors=20, learning_rate=0.01, reg=0.02, num_epochs=5, verbose=False
):
    global user_bias, item_bias, user_factors, item_factors, global_mean

    if verbose:
        print("=" * 50)
        print(f"Testing config:")
        print(f"  num_factors   = {num_factors}")
        print(f"  learning_rate = {learning_rate}")
        print(f"  reg           = {reg}")
        print(f"  epochs        = {num_epochs}")
        print("=" * 50)

    # Re-init parameters fresh for each run
    global_mean = np.mean([r for (_, _, r) in train_triplets])
    user_bias = np.zeros(num_users, dtype=np.float32)
    item_bias = np.zeros(num_items, dtype=np.float32)
    user_factors = 0.1 * np.random.randn(num_users, num_factors).astype(np.float32)
    item_factors = 0.1 * np.random.randn(num_items, num_factors).astype(np.float32)

    # Train SVD (you may want verbose=False in train_svd_sgd too)
    best_val_rmse = train_svd_sgd(
        train_triplets=train_triplets,
        val_triplets=val_dense_triplets,
        num_epochs=num_epochs,
        learning_rate=learning_rate,
        reg=reg,
    )

    return {
        "k": num_factors,
        "lr": learning_rate,
        "reg": reg,
        "epochs": num_epochs,
        "rmse": best_val_rmse,
    }

In [16]:
results = []

for k in [10, 20, 30, 40]:
    for lr in [0.02, 0.01, 0.005]:
        for reg in [0.005, 0.02, 0.05]:
            res = test_svd_config(
                num_factors=k,
                learning_rate=lr,
                reg=reg,
                num_epochs=10,
                verbose=False,  # no spam
            )
            results.append(res)

Epoch 1/10 - Train RMSE: 1.035853705440554 | Val RMSE: 0.9899413800391912
Epoch 2/10 - Train RMSE: 0.9427971562292671 | Val RMSE: 0.960825002966446
Epoch 3/10 - Train RMSE: 0.9086235366635842 | Val RMSE: 0.950572869284402
Epoch 4/10 - Train RMSE: 0.8893510943090202 | Val RMSE: 0.9457777236952668
Epoch 5/10 - Train RMSE: 0.8751843785131206 | Val RMSE: 0.9433490294543938
Epoch 6/10 - Train RMSE: 0.8627560470794315 | Val RMSE: 0.9421922531634159
Epoch 7/10 - Train RMSE: 0.8503114332767391 | Val RMSE: 0.9420914573602567
Epoch 8/10 - Train RMSE: 0.8366920677671018 | Val RMSE: 0.9424338194194678
Epoch 9/10 - Train RMSE: 0.8211444949708182 | Val RMSE: 0.9428031199454419
Epoch 10/10 - Train RMSE: 0.8038607863940342 | Val RMSE: 0.9449134727183739
Best validation RMSE: 0.9420914573602567
Epoch 1/10 - Train RMSE: 1.036397630265788 | Val RMSE: 0.9896093607742568
Epoch 2/10 - Train RMSE: 0.9437941207665149 | Val RMSE: 0.9614855833015633
Epoch 3/10 - Train RMSE: 0.9100675713230038 | Val RMSE: 0.9506952445201975
Epoch 4/10 - Train RMSE: 0.8914180639141344 | Val RMSE: 0.9459768260615511
Epoch 5/10 - Train RMSE: 0.8781037685833234 | Val RMSE: 0.9432794051150455
Epoch 6/10 - Train RMSE: 0.8672328612366922 | Val RMSE: 0.9418703357690282
Epoch 7/10 - Train RMSE: 0.8565617744998528 | Val RMSE: 0.9417190861522647
Epoch 8/10 - Train RMSE: 0.8457649739032979 | Val RMSE: 0.9415275253665131
Epoch 9/10 - Train RMSE: 0.8334355199338824 | Val RMSE: 0.9421155030321244
Epoch 10/10 - Train RMSE: 0.8195493812012004 | Val RMSE: 0.943831263443695
Best validation RMSE: 0.9415275253665131
Epoch 1/10 - Train RMSE: 1.0368422995241848 | Val RMSE: 0.9917008992941353
Epoch 2/10 - Train RMSE: 0.945041711211228 | Val RMSE: 0.961488269232096
Epoch 3/10 - Train RMSE: 0.9117968096150209 | Val RMSE: 0.9506548492132829
Epoch 4/10 - Train RMSE: 0.8937022747094456 | Val RMSE: 0.9455086117457127
Epoch 5/10 - Train RMSE: 0.8812788932266649 | Val RMSE: 0.9423977921508284
Epoch 6/10 - Train RMSE: 0.8716813015869452 | Val RMSE: 0.9413215178396879
Epoch 7/10 - Train RMSE: 0.8627663311175128 | Val RMSE: 0.93991836164445
Epoch 8/10 - Train RMSE: 0.8540990771834587 | Val RMSE: 0.9396146426265538
Epoch 9/10 - Train RMSE: 0.8449035952541661 | Val RMSE: 0.9393015855789912
Epoch 10/10 - Train RMSE: 0.8346016053838242 | Val RMSE: 0.9395617749024088
Best validation RMSE: 0.9393015855789912
Epoch 1/10 - Train RMSE: 1.065613095136724 | Val RMSE: 1.0286264445700564
Epoch 2/10 - Train RMSE: 0.9862277760127905 | Val RMSE: 0.9902401728958412
Epoch 3/10 - Train RMSE: 0.9464559833272075 | Val RMSE: 0.97146182026141
Epoch 4/10 - Train RMSE: 0.9226979604446158 | Val RMSE: 0.9610702841654831
Epoch 5/10 - Train RMSE: 0.9066666777628067 | Val RMSE: 0.9546182981443263
Epoch 6/10 - Train RMSE: 0.8948144915791233 | Val RMSE: 0.9505205900719782
Epoch 7/10 - Train RMSE: 0.8854722355820822 | Val RMSE: 0.947736551348375
Epoch 8/10 - Train RMSE: 0.877603017876275 | Val RMSE: 0.9458285686968677
Epoch 9/10 - Train RMSE: 0.87072572043319 | Val RMSE: 0.9444903176495838
Epoch 10/10 - Train RMSE: 0.8643745563613543 | Val RMSE: 0.9436043948132564
Best validation RMSE: 0.9436043948132564
Epoch 1/10 - Train RMSE: 1.0657024752705093 | Val RMSE: 1.028701328980987
Epoch 2/10 - Train RMSE: 0.9863532115587157 | Val RMSE: 0.9903251942278435
Epoch 3/10 - Train RMSE: 0.9467600762969142 | Val RMSE: 0.9717921318982508
Epoch 4/10 - Train RMSE: 0.9231111459094579 | Val RMSE: 0.96155100351913
Epoch 5/10 - Train RMSE: 0.9071496044058827 | Val RMSE: 0.9552190463330376
Epoch 6/10 - Train RMSE: 0.8954808676042346 | Val RMSE: 0.9510711385900537
Epoch 7/10 - Train RMSE: 0.8862469042268578 | Val RMSE: 0.948182956869956
Epoch 8/10 - Train RMSE: 0.8785378972358598 | Val RMSE: 0.9462145701453696
Epoch 9/10 - Train RMSE: 0.8718414446249374 | Val RMSE: 0.9448525142860797
Epoch 10/10 - Train RMSE: 0.8656739927099921 | Val RMSE: 0.9438611201265322
Best validation RMSE: 0.9438611201265322
Epoch 1/10 - Train RMSE: 1.066025220537709 | Val RMSE: 1.029022407740453
Epoch 2/10 - Train RMSE: 0.9874067638262662 | Val RMSE: 0.9910881638294498
Epoch 3/10 - Train RMSE: 0.9482380938066964 | Val RMSE: 0.9722649384048928
Epoch 4/10 - Train RMSE: 0.9248573272933671 | Val RMSE: 0.9617837342744909
Epoch 5/10 - Train RMSE: 0.9092056739071586 | Val RMSE: 0.9550506449619582
Epoch 6/10 - Train RMSE: 0.8978641321396875 | Val RMSE: 0.9506392199342297
Epoch 7/10 - Train RMSE: 0.8890165221959898 | Val RMSE: 0.9476315239004032
Epoch 8/10 - Train RMSE: 0.8819235868005176 | Val RMSE: 0.9453537830204786
Epoch 9/10 - Train RMSE: 0.8757541159168072 | Val RMSE: 0.9438129697454875
Epoch 10/10 - Train RMSE: 0.870412636059528 | Val RMSE: 0.9425553304492608
Best validation RMSE: 0.9425553304492608
Epoch 1/10 - Train RMSE: 1.0881178985084692 | Val RMSE: 1.064236221984971
Epoch 2/10 - Train RMSE: 1.0317232379462864 | Val RMSE: 1.0285582115615395
Epoch 3/10 - Train RMSE: 0.9944161103943735 | Val RMSE: 1.0056371684487895
Epoch 4/10 - Train RMSE: 0.9682692497061003 | Val RMSE: 0.9901979482091471
Epoch 5/10 - Train RMSE: 0.9490533585699963 | Val RMSE: 0.9793609714632707
Epoch 6/10 - Train RMSE: 0.9343722970834786 | Val RMSE: 0.9715087039077795
Epoch 7/10 - Train RMSE: 0.9227409569147856 | Val RMSE: 0.9656194109097896
Epoch 8/10 - Train RMSE: 0.9132545595662509 | Val RMSE: 0.9610846347182147
Epoch 9/10 - Train RMSE: 0.9053289338159533 | Val RMSE: 0.957510318086564
Epoch 10/10 - Train RMSE: 0.8985353361525473 | Val RMSE: 0.9546697749058698
Best validation RMSE: 0.9546697749058698
Epoch 1/10 - Train RMSE: 1.0882312838163466 | Val RMSE: 1.0642943405163279
Epoch 2/10 - Train RMSE: 1.0319757466803277 | Val RMSE: 1.0287052269692585
Epoch 3/10 - Train RMSE: 0.9947712077523125 | Val RMSE: 1.0058815706504833
Epoch 4/10 - Train RMSE: 0.9687766288858674 | Val RMSE: 0.990497185497214
Epoch 5/10 - Train RMSE: 0.9497029556152308 | Val RMSE: 0.9796805143641414
Epoch 6/10 - Train RMSE: 0.9351068462321468 | Val RMSE: 0.9718174110921209
Epoch 7/10 - Train RMSE: 0.9235734827935489 | Val RMSE: 0.9658753937477801
Epoch 8/10 - Train RMSE: 0.9141540390379282 | Val RMSE: 0.961335475742128
Epoch 9/10 - Train RMSE: 0.9063269420770456 | Val RMSE: 0.9577326832441828
Epoch 10/10 - Train RMSE: 0.8996354089858406 | Val RMSE: 0.9548644710178136
Best validation RMSE: 0.9548644710178136
Epoch 1/10 - Train RMSE: 1.088399527756842 | Val RMSE: 1.064842709643499
Epoch 2/10 - Train RMSE: 1.0324627140125295 | Val RMSE: 1.0294780246984736
Epoch 3/10 - Train RMSE: 0.99559285692551 | Val RMSE: 1.0066723369687909
Epoch 4/10 - Train RMSE: 0.9698460773254657 | Val RMSE: 0.9913033152158462
Epoch 5/10 - Train RMSE: 0.950982247969772 | Val RMSE: 0.9804822154153041
Epoch 6/10 - Train RMSE: 0.9365441383686127 | Val RMSE: 0.9725345356280859
Epoch 7/10 - Train RMSE: 0.9251390948651047 | Val RMSE: 0.9665546736492209
Epoch 8/10 - Train RMSE: 0.9158884310548714 | Val RMSE: 0.9619004684378494
Epoch 9/10 - Train RMSE: 0.9082036896304346 | Val RMSE: 0.958245986356953
Epoch 10/10 - Train RMSE: 0.9017068382527091 | Val RMSE: 0.9552679561797816
Best validation RMSE: 0.9552679561797816
Epoch 1/10 - Train RMSE: 1.036462025212556 | Val RMSE: 0.9906214106532684
Epoch 2/10 - Train RMSE: 0.9396639284796792 | Val RMSE: 0.9623003930032031
Epoch 3/10 - Train RMSE: 0.9019817984649626 | Val RMSE: 0.951925137589083
Epoch 4/10 - Train RMSE: 0.8786672963721406 | Val RMSE: 0.9476010412636672
Epoch 5/10 - Train RMSE: 0.8597030541944108 | Val RMSE: 0.9455029048440402
Epoch 6/10 - Train RMSE: 0.8415260165169957 | Val RMSE: 0.9453099778422144
Epoch 7/10 - Train RMSE: 0.8220807314903699 | Val RMSE: 0.9452406321852618
Epoch 8/10 - Train RMSE: 0.800165954814153 | Val RMSE: 0.9467288700064498
Epoch 9/10 - Train RMSE: 0.7750000632269031 | Val RMSE: 0.949360579577169
Epoch 10/10 - Train RMSE: 0.7467952436001404 | Val RMSE: 0.9536028256602013
Best validation RMSE: 0.9452406321852618
Epoch 1/10 - Train RMSE: 1.0370643124586012 | Val RMSE: 0.9902718358848248
Epoch 2/10 - Train RMSE: 0.9405814987364206 | Val RMSE: 0.9615562965262228
Epoch 3/10 - Train RMSE: 0.9031713385485041 | Val RMSE: 0.9516883702488808
Epoch 4/10 - Train RMSE: 0.8807954445533268 | Val RMSE: 0.9466360230090589
Epoch 5/10 - Train RMSE: 0.8630653446656266 | Val RMSE: 0.9443241608159895
Epoch 6/10 - Train RMSE: 0.8465962666480987 | Val RMSE: 0.9436472454624539
Epoch 7/10 - Train RMSE: 0.8296523748180349 | Val RMSE: 0.9437697248641566
Epoch 8/10 - Train RMSE: 0.8106759530599542 | Val RMSE: 0.9446019557429055
Epoch 9/10 - Train RMSE: 0.7891855905713901 | Val RMSE: 0.9462192360129027
Epoch 10/10 - Train RMSE: 0.7649751659470373 | Val RMSE: 0.9486047302775519
Best validation RMSE: 0.9436472454624539
Epoch 1/10 - Train RMSE: 1.0371674092896215 | Val RMSE: 0.9915675067561788
Epoch 2/10 - Train RMSE: 0.9414763249000361 | Val RMSE: 0.9629645172825954
Epoch 3/10 - Train RMSE: 0.9056344178788771 | Val RMSE: 0.9521102148269984
Epoch 4/10 - Train RMSE: 0.8844996155427853 | Val RMSE: 0.9473751395145077
Epoch 5/10 - Train RMSE: 0.8691639054406372 | Val RMSE: 0.9452275782735753
Epoch 6/10 - Train RMSE: 0.8556899296695517 | Val RMSE: 0.9435614364733502
Epoch 7/10 - Train RMSE: 0.8428879952242064 | Val RMSE: 0.9429491640178003
Epoch 8/10 - Train RMSE: 0.8293486623264097 | Val RMSE: 0.9425138069781279
Epoch 9/10 - Train RMSE: 0.8143352770195675 | Val RMSE: 0.943004996052508
Epoch 10/10 - Train RMSE: 0.7978420221773341 | Val RMSE: 0.944133947910365
Best validation RMSE: 0.9425138069781279
Epoch 1/10 - Train RMSE: 1.0662865602881564 | Val RMSE: 1.029190359488828
Epoch 2/10 - Train RMSE: 0.9847801587641346 | Val RMSE: 0.9910183819696385
Epoch 3/10 - Train RMSE: 0.9432013525789504 | Val RMSE: 0.9726236030704992
Epoch 4/10 - Train RMSE: 0.9176835492019308 | Val RMSE: 0.9620420592586433
Epoch 5/10 - Train RMSE: 0.8998168378605633 | Val RMSE: 0.9558501013996822
Epoch 6/10 - Train RMSE: 0.8859691569014243 | Val RMSE: 0.9517506777584965
Epoch 7/10 - Train RMSE: 0.8744728582825543 | Val RMSE: 0.9489577656943324
Epoch 8/10 - Train RMSE: 0.8642534737155609 | Val RMSE: 0.947056975581824
Epoch 9/10 - Train RMSE: 0.8547879589372007 | Val RMSE: 0.9457836114258021
Epoch 10/10 - Train RMSE: 0.8455290611651172 | Val RMSE: 0.9448047001180236
Best validation RMSE: 0.9448047001180236
Epoch 1/10 - Train RMSE: 1.066003228481398 | Val RMSE: 1.028667605445173
Epoch 2/10 - Train RMSE: 0.9849005301973689 | Val RMSE: 0.990469541325012
Epoch 3/10 - Train RMSE: 0.9436267479349191 | Val RMSE: 0.972079598912919
Epoch 4/10 - Train RMSE: 0.918342853576677 | Val RMSE: 0.9614731066618369
Epoch 5/10 - Train RMSE: 0.9007486964716869 | Val RMSE: 0.9550221901287919
Epoch 6/10 - Train RMSE: 0.8872829916745364 | Val RMSE: 0.9508672153463084
Epoch 7/10 - Train RMSE: 0.8762594066120132 | Val RMSE: 0.9480213179449865
Epoch 8/10 - Train RMSE: 0.8666991136402865 | Val RMSE: 0.9459511854323556
Epoch 9/10 - Train RMSE: 0.8578857928992184 | Val RMSE: 0.9444450570061399
Epoch 10/10 - Train RMSE: 0.8494978038176279 | Val RMSE: 0.9433984215424716
Best validation RMSE: 0.9433984215424716
Epoch 1/10 - Train RMSE: 1.0667249032146768 | Val RMSE: 1.02977564385282
Epoch 2/10 - Train RMSE: 0.9861228810767021 | Val RMSE: 0.9918957226912067
Epoch 3/10 - Train RMSE: 0.9451856168606314 | Val RMSE: 0.9730752460043189
Epoch 4/10 - Train RMSE: 0.9202633273170148 | Val RMSE: 0.9625221592789722
Epoch 5/10 - Train RMSE: 0.9031909026290494 | Val RMSE: 0.9559972903640782
Epoch 6/10 - Train RMSE: 0.8903401754255543 | Val RMSE: 0.9515393043868632
Epoch 7/10 - Train RMSE: 0.880058049896766 | Val RMSE: 0.9484204326163005
Epoch 8/10 - Train RMSE: 0.8713122396896813 | Val RMSE: 0.946179718271054
Epoch 9/10 - Train RMSE: 0.8635402791618375 | Val RMSE: 0.944511322356822
Epoch 10/10 - Train RMSE: 0.8564406066027322 | Val RMSE: 0.9434525831284952
Best validation RMSE: 0.9434525831284952
Epoch 1/10 - Train RMSE: 1.0886846637243786 | Val RMSE: 1.0648308486320164
Epoch 2/10 - Train RMSE: 1.031186836073359 | Val RMSE: 1.0290869504312254
Epoch 3/10 - Train RMSE: 0.992880248165524 | Val RMSE: 1.0062176913712673
Epoch 4/10 - Train RMSE: 0.9658800342523456 | Val RMSE: 0.9908772860298913
Epoch 5/10 - Train RMSE: 0.9458189795212939 | Val RMSE: 0.9800958601904189
Epoch 6/10 - Train RMSE: 0.9302531795642516 | Val RMSE: 0.972307579290226
Epoch 7/10 - Train RMSE: 0.9177283471924826 | Val RMSE: 0.9664420977869559
Epoch 8/10 - Train RMSE: 0.9073236499092996 | Val RMSE: 0.9619330029679961
Epoch 9/10 - Train RMSE: 0.8984644748798816 | Val RMSE: 0.9584446779559307
Epoch 10/10 - Train RMSE: 0.8907204963200244 | Val RMSE: 0.955666438286995
Best validation RMSE: 0.955666438286995
Epoch 1/10 - Train RMSE: 1.0888070812789896 | Val RMSE: 1.0648534673380181
Epoch 2/10 - Train RMSE: 1.0315069633525742 | Val RMSE: 1.0293294987762658
Epoch 3/10 - Train RMSE: 0.9934214802346724 | Val RMSE: 1.0065669502169299
Epoch 4/10 - Train RMSE: 0.9665407103645578 | Val RMSE: 0.9912003295601938
Epoch 5/10 - Train RMSE: 0.9465994905770194 | Val RMSE: 0.9804105264102468
Epoch 6/10 - Train RMSE: 0.931165119798712 | Val RMSE: 0.9725095135634392
Epoch 7/10 - Train RMSE: 0.9187823339645862 | Val RMSE: 0.9665811486552721
Epoch 8/10 - Train RMSE: 0.9085378942221932 | Val RMSE: 0.9620538431860215
Epoch 9/10 - Train RMSE: 0.8998524425078995 | Val RMSE: 0.9584393185129948
Epoch 10/10 - Train RMSE: 0.892283201402127 | Val RMSE: 0.9556009500833864
Best validation RMSE: 0.9556009500833864
Epoch 1/10 - Train RMSE: 1.0888842499638545 | Val RMSE: 1.064754291327598
Epoch 2/10 - Train RMSE: 1.0318695538992915 | Val RMSE: 1.0294875365292093
Epoch 3/10 - Train RMSE: 0.9940994601723727 | Val RMSE: 1.0068968426730691
Epoch 4/10 - Train RMSE: 0.9675347799932363 | Val RMSE: 0.9916301500124457
Epoch 5/10 - Train RMSE: 0.94788148957884 | Val RMSE: 0.9808850390721786
Epoch 6/10 - Train RMSE: 0.9327159202155951 | Val RMSE: 0.9730289405927305
Epoch 7/10 - Train RMSE: 0.920573123594861 | Val RMSE: 0.9670810723577637
Epoch 8/10 - Train RMSE: 0.910567904623072 | Val RMSE: 0.9624797416979937
Epoch 9/10 - Train RMSE: 0.9021353314326278 | Val RMSE: 0.9588693634518517
Epoch 10/10 - Train RMSE: 0.8948642583670992 | Val RMSE: 0.9559370570966879
Best validation RMSE: 0.9559370570966879
Epoch 1/10 - Train RMSE: 1.0374582041806737 | Val RMSE: 0.9911936587057278
Epoch 2/10 - Train RMSE: 0.9366866252872907 | Val RMSE: 0.9623203156247639
Epoch 3/10 - Train RMSE: 0.8956497948999812 | Val RMSE: 0.9523798329540137
Epoch 4/10 - Train RMSE: 0.8685084314037413 | Val RMSE: 0.9479191240977641
Epoch 5/10 - Train RMSE: 0.8451276413669029 | Val RMSE: 0.9459148957038054
Epoch 6/10 - Train RMSE: 0.8216963131772413 | Val RMSE: 0.945458696307225
Epoch 7/10 - Train RMSE: 0.796174941329484 | Val RMSE: 0.9469173806811066
Epoch 8/10 - Train RMSE: 0.7672588281835299 | Val RMSE: 0.9489522121320048
Epoch 9/10 - Train RMSE: 0.7346692541042144 | Val RMSE: 0.9514155780316361
Epoch 10/10 - Train RMSE: 0.6987854154883862 | Val RMSE: 0.9559957089116276
Best validation RMSE: 0.945458696307225
Epoch 1/10 - Train RMSE: 1.037273458798954 | Val RMSE: 0.9912734348782477
Epoch 2/10 - Train RMSE: 0.9367648962772644 | Val RMSE: 0.9626688552629887
Epoch 3/10 - Train RMSE: 0.8961004744378088 | Val RMSE: 0.952231480364632
Epoch 4/10 - Train RMSE: 0.8697377820202435 | Val RMSE: 0.9475047392688597
Epoch 5/10 - Train RMSE: 0.8478966470206712 | Val RMSE: 0.9454321076109418
Epoch 6/10 - Train RMSE: 0.8266446238490479 | Val RMSE: 0.9445016853450748
Epoch 7/10 - Train RMSE: 0.8039314879692256 | Val RMSE: 0.9450442905952459
Epoch 8/10 - Train RMSE: 0.7786945783793302 | Val RMSE: 0.9458722139834932
Epoch 9/10 - Train RMSE: 0.7503602189894273 | Val RMSE: 0.9478104441567397
Epoch 10/10 - Train RMSE: 0.719126084020216 | Val RMSE: 0.9504983358353964
Best validation RMSE: 0.9445016853450748
Epoch 1/10 - Train RMSE: 1.0378979057710676 | Val RMSE: 0.991768427998616
Epoch 2/10 - Train RMSE: 0.9385027333859276 | Val RMSE: 0.9629108833266689
Epoch 3/10 - Train RMSE: 0.8995657681180927 | Val RMSE: 0.9513974923440135
Epoch 4/10 - Train RMSE: 0.8756006021743991 | Val RMSE: 0.9467558730706803
Epoch 5/10 - Train RMSE: 0.8570301467986368 | Val RMSE: 0.9439009918547527
Epoch 6/10 - Train RMSE: 0.8401622691709029 | Val RMSE: 0.9421915796352688
Epoch 7/10 - Train RMSE: 0.8232220958815012 | Val RMSE: 0.9412937459690228
Epoch 8/10 - Train RMSE: 0.805177483436421 | Val RMSE: 0.9411428983259286
Epoch 9/10 - Train RMSE: 0.7851472304758317 | Val RMSE: 0.9414421013195339
Epoch 10/10 - Train RMSE: 0.763148297582104 | Val RMSE: 0.9422615094381465
Best validation RMSE: 0.9411428983259286
Epoch 1/10 - Train RMSE: 1.0664581031375573 | Val RMSE: 1.0299074612562962
Epoch 2/10 - Train RMSE: 0.9829207720045743 | Val RMSE: 0.9919318274455632
Epoch 3/10 - Train RMSE: 0.9394653440985629 | Val RMSE: 0.9734253970886406
Epoch 4/10 - Train RMSE: 0.9120792840411241 | Val RMSE: 0.9630612802968184
Epoch 5/10 - Train RMSE: 0.8922367745627415 | Val RMSE: 0.9568362922230318
Epoch 6/10 - Train RMSE: 0.8763609218223908 | Val RMSE: 0.9527967861035801
Epoch 7/10 - Train RMSE: 0.8626844730097942 | Val RMSE: 0.9501486914493714
Epoch 8/10 - Train RMSE: 0.8500842576617649 | Val RMSE: 0.9483151844472401
Epoch 9/10 - Train RMSE: 0.8379926996053447 | Val RMSE: 0.9470888415069704
Epoch 10/10 - Train RMSE: 0.8259580985550412 | Val RMSE: 0.9464500822565285
Best validation RMSE: 0.9464500822565285
Epoch 1/10 - Train RMSE: 1.0669459674299488 | Val RMSE: 1.0300396969490704
Epoch 2/10 - Train RMSE: 0.9838274883769881 | Val RMSE: 0.9921602586627825
Epoch 3/10 - Train RMSE: 0.9406665600577088 | Val RMSE: 0.9736261012667907
Epoch 4/10 - Train RMSE: 0.9136716704491016 | Val RMSE: 0.9632222903316003
Epoch 5/10 - Train RMSE: 0.8943744513044491 | Val RMSE: 0.9570515253728934
Epoch 6/10 - Train RMSE: 0.8791560078109064 | Val RMSE: 0.9528573895201967
Epoch 7/10 - Train RMSE: 0.866221301150687 | Val RMSE: 0.9500074497538293
Epoch 8/10 - Train RMSE: 0.8545837078473228 | Val RMSE: 0.948081147632266
Epoch 9/10 - Train RMSE: 0.8436340058422053 | Val RMSE: 0.9467406102137867
Epoch 10/10 - Train RMSE: 0.8328875985725452 | Val RMSE: 0.9457882434415743
Best validation RMSE: 0.9457882434415743
Epoch 1/10 - Train RMSE: 1.0669151770950767 | Val RMSE: 1.0301016170333048
Epoch 2/10 - Train RMSE: 0.9844275742832166 | Val RMSE: 0.9922907925764136
Epoch 3/10 - Train RMSE: 0.9421141772305113 | Val RMSE: 0.97373733670046
Epoch 4/10 - Train RMSE: 0.9158141781891196 | Val RMSE: 0.9630145273107956
Epoch 5/10 - Train RMSE: 0.8973293441801221 | Val RMSE: 0.9564025410127402
Epoch 6/10 - Train RMSE: 0.8831227910982921 | Val RMSE: 0.9520691610186018
Epoch 7/10 - Train RMSE: 0.8714171197871865 | Val RMSE: 0.9488891113682536
Epoch 8/10 - Train RMSE: 0.8612461605107363 | Val RMSE: 0.9467169130228855
Epoch 9/10 - Train RMSE: 0.8519984401409871 | Val RMSE: 0.9452445028729161
Epoch 10/10 - Train RMSE: 0.8433188395480568 | Val RMSE: 0.9439228744707477
Best validation RMSE: 0.9439228744707477
Epoch 1/10 - Train RMSE: 1.0889746162310048 | Val RMSE: 1.0658699103084193
Epoch 2/10 - Train RMSE: 1.030482853307322 | Val RMSE: 1.0302474699070194
Epoch 3/10 - Train RMSE: 0.9912642947535719 | Val RMSE: 1.0073905316667502
Epoch 4/10 - Train RMSE: 0.9633672162736483 | Val RMSE: 0.9920278544755817
Epoch 5/10 - Train RMSE: 0.9424658424742778 | Val RMSE: 0.9812876244698799
Epoch 6/10 - Train RMSE: 0.9260562100315846 | Val RMSE: 0.9734620823259688
Epoch 7/10 - Train RMSE: 0.9126863665834125 | Val RMSE: 0.9675623958721934
Epoch 8/10 - Train RMSE: 0.9014350843017919 | Val RMSE: 0.963107187769216
Epoch 9/10 - Train RMSE: 0.8917127102837253 | Val RMSE: 0.9596033126066656
Epoch 10/10 - Train RMSE: 0.8830720968234115 | Val RMSE: 0.9568319075977678
Best validation RMSE: 0.9568319075977678
Epoch 1/10 - Train RMSE: 1.0894292260465874 | Val RMSE: 1.0659794870209733
Epoch 2/10 - Train RMSE: 1.0310726980212388 | Val RMSE: 1.0304431771542397
Epoch 3/10 - Train RMSE: 0.9920213714471711 | Val RMSE: 1.0076735035543067

In [17]:
# Sort by RMSE ascending
results_sorted = sorted(results, key=lambda x: x["rmse"])
best = results_sorted[0]

print("=== Best configuration found ===")
print(f"k       = {best['k']}")
print(f"lr      = {best['lr']}")
print(f"reg     = {best['reg']}")
print(f"epochs  = {best['epochs']}")
print(f"RMSE    = {best['rmse']:.4f}")

=== Best configuration found ===
k       = 10
lr      = 0.02
reg     = 0.05
epochs  = 10
RMSE    = 0.9393

In [18]:
movies_df.head()

   movieId                               title                        genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [19]:
# Building CBF model

# Build genre vocabulary from movies_df
all_genres = set()

for g_str in movies_df["genres"]:
    for g in str(g_str).split("|"):
        g = g.strip()
        # print(g)

        if g and g != "(no genres listed)":
            all_genres.add(g)

all_genres = sorted(all_genres)
genre_to_idx = {g: idx for idx, g in enumerate(all_genres)}
num_genres = len(all_genres)

print("Number of genres:", num_genres)
print("Genres:", all_genres)

Number of genres: 18
Genres: ['Action', 'Adventure', 'Animation', "Children's", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

In [20]:
# Build item_genre_matrix aligned with internal item_idx
item_genre_matrix = np.zeros((num_items, num_genres), dtype=np.float32)

# Map movieId -> genres string for quick lookup
movie_genres_map = dict(zip(movies_df["movieId"], movies_df["genres"]))

for internal_i in range(num_items):
    movie_id = reverse_item_map[internal_i]  # original MovieID
    g_str = movie_genres_map.get(movie_id, "")

    for g in str(g_str).split("|"):
        g = g.strip()

        if g in genre_to_idx:
            item_genre_matrix[internal_i, genre_to_idx[g]] = 1.0  # one hot-encoding

In [21]:
from collections import defaultdict
import numpy as np

# Build user_ratings from TRAIN
user_ratings = defaultdict(list)
for u, i, r in train_triplets:
    user_ratings[u].append((i, r))

user_profiles = np.zeros((num_users, num_genres), dtype=np.float32)

for u, rated_list in user_ratings.items():
    # mean rating for this user (TRAIN only)
    ratings = [r for (_, r) in rated_list]
    mu = float(np.mean(ratings))

    profile = np.zeros(num_genres, dtype=np.float32)
    total_weight = 0.0

    for i, r in rated_list:
        w = max(r - mu, 0.0)  # only above-mean contribute
        if w <= 0:
            continue
        profile += w * item_genre_matrix[i]
        total_weight += w

    if total_weight > 0:
        user_profiles[u] = profile / total_weight
    # else: leave as all zeros

In [22]:
user_rated_items = defaultdict(set)
for u, i, r in train_triplets:
    user_rated_items[u].add(i)

In [23]:
def cbf_score(u, i):
    user_vec = user_profiles[u]
    item_vec = item_genre_matrix[i]

    # If user profile or item vector is all zeros, fall back to global mean
    norm_u = np.linalg.norm(user_vec)
    norm_i = np.linalg.norm(item_vec)
    if norm_u == 0.0 or norm_i == 0.0:
        return global_mean  # from SVD setup

    sim = np.dot(user_vec, item_vec) / (norm_u * norm_i)  # cosine similarity

    # For our non-negative vectors, sim is between 0 and 1.
    # Map similarity [0,1] to rating [1,5]:
    return 1.0 + 4.0 * sim

In [24]:
# pick a user and two items
u = 0
i1 = 0
i2 = 1

print("CBF score for user 0, item 0:", cbf_score(u, i1))
print("CBF score for user 0, item 1:", cbf_score(u, i2))

CBF score for user 0, item 0: 1.0
CBF score for user 0, item 1: 3.6415631771087646

In [25]:
from collections import Counter

user_train_counts = Counter(u for u, _, _ in train_triplets)
item_train_counts = Counter(i for _, i, _ in train_triplets)

print("Example user counts:", list(user_train_counts.items())[:10])
print("Example item counts:", list(item_train_counts.items())[:10])

Example user counts: [(1250, 38), (379, 29), (551, 44), (455, 165), (2033, 17), (630, 87), (1644, 35), (1322, 65), (202, 49), (1678, 21)]
Example item counts: [(678, 92), (2595, 4), (462, 13), (1161, 15), (1598, 46), (644, 55), (3206, 4), (570, 31), (1360, 10), (1237, 24)]

In [26]:
ITEM_MIN_CF = 5  # below this, CF is considered unreliable for the item
ALPHA = 0.9  # CF weight when item is NOT sparse

In [27]:
def hybrid_score(u, i):
    n_i = item_train_counts.get(i, 0)  # #ratings for item i in TRAIN

    cf_pred = svd_score(u, i)  # CF (SVD) prediction
    cbf_pred = cbf_score(u, i)  # CBF prediction

    # If the ITEM is sparse, trust only CBF (CF is unreliable here)
    if n_i < ITEM_MIN_CF:
        return cbf_pred

    # Otherwise: blend CF + CBF (CBF still helps in all other cases)
    return ALPHA * cf_pred + (1.0 - ALPHA) * cbf_pred

In [28]:
def rmse_for_scorer(triplets, score_fn):
    se = 0.0
    for u, i, r in triplets:
        pred = score_fn(u, i)
        se += (r - pred) ** 2
    return np.sqrt(se / len(triplets))

In [29]:
all_test_triplets = test_dense_triplets + cold_triplets

# print("=== CF (SVD) ===")
# rmse_dense_cf = rmse_for_scorer(test_dense_triplets, svd_score)
# rmse_cold_cf = rmse_for_scorer(cold_triplets, svd_score)
# rmse_all_cf = rmse_for_scorer(all_test_triplets, svd_score)
# print(f"RMSE dense users : {rmse_dense_cf:.4f}")
# print(f"RMSE cold users  : {rmse_cold_cf:.4f}")
# print(f"RMSE all users   : {rmse_all_cf:.4f}")

# print("\n=== CBF ===")
# rmse_dense_cbf = rmse_for_scorer(test_dense_triplets, cbf_score)
# rmse_cold_cbf = rmse_for_scorer(cold_triplets, cbf_score)
# rmse_all_cbf = rmse_for_scorer(all_test_triplets, cbf_score)
# print(f"RMSE dense users : {rmse_dense_cbf:.4f}")
# print(f"RMSE cold users  : {rmse_cold_cbf:.4f}")
# print(f"RMSE all users   : {rmse_all_cbf:.4f}")

# print("\n=== Hybrid (CF+CBF) ===")
# rmse_dense_h = rmse_for_scorer(test_dense_triplets, hybrid_score)
# rmse_cold_h = rmse_for_scorer(cold_triplets, hybrid_score)
# rmse_all_h = rmse_for_scorer(all_test_triplets, hybrid_score)
# print(f"RMSE dense users : {rmse_dense_h:.4f}")
# print(f"RMSE cold users  : {rmse_cold_h:.4f}")
# print(f"RMSE all users   : {rmse_all_h:.4f}")

In [30]:
# Serendipity measure


def build_user_ratings(triplets):
    user_ratings = defaultdict(list)
    for u, i, r in triplets:
        user_ratings[u].append((i, r))
    return user_ratings


def cosine_similarity(a, b):
    na = np.linalg.norm(a)
    nb = np.linalg.norm(b)
    if na == 0.0 or nb == 0.0:
        return None
    return float(np.dot(a, b) / (na * nb))


def item_unexpectedness(u, i):
    """1 - cosine similarity between user profile and item genres."""
    u_vec = user_profiles[u]
    i_vec = item_genre_matrix[i]

    sim = cosine_similarity(u_vec, i_vec)
    if sim is None:
        return None
    return 1.0 - sim


def top_k_for_user(u, user_ratings, score_fn, top_k):
    """
    user_ratings[u] is a list of (item, true_rating) for that user in TEST.
    """
    scored = []
    for i, r_true in user_ratings[u]:
        pred = score_fn(u, i)
        scored.append((pred, i, r_true))

    scored.sort(reverse=True, key=lambda x: x[0])
    return scored[:top_k]


def serendipity_for_user(u, user_ratings, score_fn, top_k=10, rel_thresh=4.0):
    top = top_k_for_user(u, user_ratings, score_fn, top_k)

    num = 0.0
    den = 0

    for _, i, r_true in top:
        if r_true < rel_thresh:
            continue  # only count actually relevant items

        unexp = item_unexpectedness(u, i)
        if unexp is None:
            continue

        num += unexp
        den += 1

    if den == 0:
        return None

    return num / den

In [31]:
# Building NCF implementation -- RS2

import pandas as pd
import numpy as np

users_file = "../dataset/users.dat"

user_columns = ["user_id", "gender", "age", "occupation", "zipcode"]

users_raw = pd.read_csv(
    users_file,
    sep="::",
    engine="python",
    names=user_columns,
)

print(users_raw.shape)

users_raw.head()

(6040, 5)

   user_id gender  age  occupation zipcode
0        1      F    1          10   48067
1        2      M   56          16   70072
2        3      M   25          15   55117
3        4      M   45           7   02460
4        5      M   25          20   55455

In [32]:
# Make a working copy
users_df = users_raw.copy()

# Map gender to 0/1
users_df["gender"] = users_df["gender"].map({"M": 0, "F": 1}).astype(np.int64)

# Ensure age and occupation are integers
users_df["age"] = users_df["age"].astype(np.int64)
users_df["occupation"] = users_df["occupation"].astype(np.int64)

users_df.head()

   user_id  gender  age  occupation zipcode
0        1       1    1          10   48067
1        2       0   56          16   70072
2        3       0   25          15   55117
3        4       0   45           7   02460
4        5       0   25          20   55455

In [33]:
# Add internal user_idx using the same mapping as CF/CBF
users_df["user_idx"] = users_df["user_id"].map(user_map)

# Keep only users that actually appear in ratings_sample
users_df = users_df.dropna(subset=["user_idx"]).copy()
users_df["user_idx"] = users_df["user_idx"].astype(int)

# For sanity: sort by user_idx and keep only what we need for RS2
user_features_df = users_df[["user_idx", "gender", "age", "occupation"]].sort_values(
    "user_idx"
)

print(
    "Num distinct internal users in features:", user_features_df["user_idx"].nunique()
)
print("num_users from earlier:", num_users)

user_features_df.head()

Num distinct internal users in features: 3067
num_users from earlier: 3067

      user_idx  gender  age  occupation
3401         0       0   35          20
4276         1       0   35          16
3677         2       0   25           0
3390         3       0   18           4
2571         4       0   35          14

In [34]:
# Ensure we have one feature row per internal user_idx in order 0..num_users-1
user_features_df = user_features_df.set_index("user_idx").reindex(range(num_users))

assert user_features_df.isna().sum().sum() == 0

user_gender = user_features_df["gender"].values.astype(np.int64)
user_age = user_features_df["age"].values.astype(np.int64)
user_occupation = user_features_df["occupation"].values.astype(np.int64)

print("user_gender shape:", user_gender.shape)
print("user_age shape:", user_age.shape)
print("user_occupation shape:", user_occupation.shape)

user_gender shape: (3067,)
user_age shape: (3067,)
user_occupation shape: (3067,)

In [35]:
import torch
import torch.nn as nn
import torch.nn.functional as F

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

num_genders = int(len(np.unique(user_gender)))
max_age_code = int(user_age.max())  # age buckets like 1,18,25,...
num_occupations = int(user_occupation.max() + 1)

print("num_users:", num_users)
print("num_items:", num_items)
print("num_genders:", num_genders)
print("max_age_code:", max_age_code)
print("num_occupations:", num_occupations)

Using device: cpu
num_users: 3067
num_items: 3341
num_genders: 2
max_age_code: 56
num_occupations: 21

In [36]:
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.nn.functional as F


class NCFHybrid(nn.Module):
    def __init__(
        self,
        num_users,
        num_items,
        num_genders,
        max_age_code,
        num_occupations,
        num_genres,
        item_genre_matrix,  # numpy array (num_items, num_genres)
        emb_dim=16,
        hidden_dim=64,
        genre_emb_dim=8,
    ):
        super().__init__()

        # === User tower ===
        self.user_emb = nn.Embedding(num_users, emb_dim)

        self.gender_emb = nn.Embedding(num_genders, 2)
        self.age_emb = nn.Embedding(max_age_code + 1, 2)
        self.occ_emb = nn.Embedding(num_occupations, 4)

        user_vec_dim = emb_dim + 2 + 2 + 4
        self.user_mlp = nn.Sequential(
            nn.Linear(user_vec_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, emb_dim),  # back to item emb dim
        )

        # === Item tower ===
        self.item_emb = nn.Embedding(num_items, emb_dim)

        # Genre embeddings
        self.genre_emb = nn.Embedding(num_genres, genre_emb_dim)

        # Store the multi-hot genre indicators as a buffer (not trainable)
        self.register_buffer(
            "item_genre_multi_hot",
            torch.tensor(item_genre_matrix, dtype=torch.float32),
        )

        # Concatenated item vector: [item_emb | summed_genre_emb]
        item_vec_dim = emb_dim + genre_emb_dim
        self.item_mlp = nn.Sequential(
            nn.Linear(item_vec_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, emb_dim),  # final item repr
        )

        # === Interaction MLP (NeuMF-style) ===
        self.interaction_mlp = nn.Sequential(
            nn.Linear(emb_dim * 2, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, 1),
        )

        self.global_bias = nn.Parameter(
            torch.tensor(float(global_mean), dtype=torch.float32)
        )

    def forward(self, user_idx, item_idx, gender, age, occupation):
        # --- user representation ---
        u_base = self.user_emb(user_idx)
        g = self.gender_emb(gender)
        a = self.age_emb(age)
        o = self.occ_emb(occupation)
        u_concat = torch.cat([u_base, g, a, o], dim=-1)
        u_repr = self.user_mlp(u_concat)  # [B, emb_dim]

        # --- item representation ---
        i_base = self.item_emb(item_idx)  # [B, emb_dim]

        # multi-hot genre indicators for these items: [B, num_genres]
        g_multi = self.item_genre_multi_hot[item_idx]

        # summed genre embedding per item: [B, genre_emb_dim]
        genre_vec = g_multi @ self.genre_emb.weight  # matmul

        i_concat = torch.cat([i_base, genre_vec], dim=-1)
        i_repr = self.item_mlp(i_concat)  # [B, emb_dim]

        # --- interaction ---
        x = torch.cat([u_repr, i_repr], dim=-1)
        out = self.interaction_mlp(x).squeeze(-1) + self.global_bias

        return torch.clamp(out, 1.0, 5.0)

In [37]:
ncf_model = NCFHybrid(
    num_users=num_users,
    num_items=num_items,
    num_genders=num_genders,
    max_age_code=max_age_code,
    num_occupations=num_occupations,
    num_genres=num_genres,
    item_genre_matrix=item_genre_matrix,
    emb_dim=16,
    hidden_dim=64,
    genre_emb_dim=8,
).to(device)

In [38]:
class NCFDataset(Dataset):
    """
    Each example: (user_idx, item_idx, gender, age, occupation, rating)
    """

    def __init__(self, triplets):
        self.users = np.array([int(u) for (u, _, _) in triplets], dtype=np.int64)
        self.items = np.array([int(i) for (_, i, _) in triplets], dtype=np.int64)
        self.ratings = np.array([float(r) for (_, _, r) in triplets], dtype=np.float32)

    def __len__(self):
        return len(self.ratings)

    def __getitem__(self, idx):
        u = self.users[idx]
        i = self.items[idx]
        r = self.ratings[idx]

        g = user_gender[u]
        a = user_age[u]
        o = user_occupation[u]

        return (
            torch.tensor(u, dtype=torch.long),
            torch.tensor(i, dtype=torch.long),
            torch.tensor(g, dtype=torch.long),
            torch.tensor(a, dtype=torch.long),
            torch.tensor(o, dtype=torch.long),
            torch.tensor(r, dtype=torch.float32),
        )


# Dense-only datasets (since SVD also trains on dense)
train_dataset_dense = NCFDataset(train_triplets)
val_dataset_dense = NCFDataset(val_dense_triplets)
val_dataset_all = NCFDataset(all_test_triplets)  # for overall eval

In [39]:
batch_size = 1024

train_loader = DataLoader(train_dataset_dense, batch_size=batch_size, shuffle=True)
val_loader_dense = DataLoader(val_dataset_dense, batch_size=batch_size, shuffle=False)
val_loader_all = DataLoader(val_dataset_all, batch_size=batch_size, shuffle=False)

In [ ]:
criterion = nn.MSELoss()
optimiser = torch.optim.Adam(ncf_model.parameters(), lr=0.001, weight_decay=0.00001)


def eval_rmse(model, data_loader):
    model.eval()
    se = 0.0
    n = 0
    with torch.no_grad():
        for u, i, g, a, o, r in data_loader:
            u = u.to(device)
            i = i.to(device)
            g = g.to(device)
            a = a.to(device)
            o = o.to(device)
            r = r.to(device)

            preds = model(u, i, g, a, o)
            se += torch.sum((preds - r) ** 2).item()
            n += r.numel()
    return np.sqrt(se / n)


# learning
num_epochs = 20
best_val_rmse = None
best_state = None

for epoch in range(1, num_epochs + 1):
    ncf_model.train()
    running_loss = 0.0
    count = 0

    for u, i, g, a, o, r in train_loader:
        u = u.to(device)
        i = i.to(device)
        g = g.to(device)
        a = a.to(device)
        o = o.to(device)
        r = r.to(device)

        optimiser.zero_grad()
        preds = ncf_model(u, i, g, a, o)
        loss = criterion(preds, r)
        loss.backward()
        optimiser.step()

        running_loss += loss.item() * r.size(0)
        count += r.size(0)

    train_rmse = np.sqrt(running_loss / count)
    val_rmse = eval_rmse(ncf_model, val_loader_dense)

    print(
        f"Epoch {epoch:02d} | train RMSE: {train_rmse:.4f} | val (dense) RMSE: {val_rmse:.4f}"
    )

    if best_val_rmse is None or val_rmse < best_val_rmse:
        best_val_rmse = val_rmse
        best_state = ncf_model.state_dict()

print("Best dense-val RMSE (NCF):", best_val_rmse)
if best_state is not None:
    ncf_model.load_state_dict(best_state)

Epoch 01 | train RMSE: 1.1092 | val (dense) RMSE: 1.0999
Epoch 02 | train RMSE: 1.0888 | val (dense) RMSE: 1.0825
Epoch 03 | train RMSE: 1.0667 | val (dense) RMSE: 1.0640
Epoch 04 | train RMSE: 1.0396 | val (dense) RMSE: 1.0433
Epoch 05 | train RMSE: 1.0152 | val (dense) RMSE: 1.0339
Epoch 06 | train RMSE: 0.9934 | val (dense) RMSE: 1.0140
Epoch 07 | train RMSE: 0.9740 | val (dense) RMSE: 1.0044
Epoch 08 | train RMSE: 0.9574 | val (dense) RMSE: 0.9927
Epoch 09 | train RMSE: 0.9434 | val (dense) RMSE: 0.9837
Epoch 10 | train RMSE: 0.9319 | val (dense) RMSE: 0.9800
Epoch 11 | train RMSE: 0.9204 | val (dense) RMSE: 0.9716
Epoch 12 | train RMSE: 0.9130 | val (dense) RMSE: 0.9693
Epoch 13 | train RMSE: 0.9034 | val (dense) RMSE: 0.9643
Epoch 14 | train RMSE: 0.8966 | val (dense) RMSE: 0.9631
Epoch 15 | train RMSE: 0.8903 | val (dense) RMSE: 0.9580
Epoch 16 | train RMSE: 0.8850 | val (dense) RMSE: 0.9586
Epoch 17 | train RMSE: 0.8815 | val (dense) RMSE: 0.9581
Epoch 18 | train RMSE: 0.8770 | val (dense) RMSE: 0.9510
Epoch 19 | train RMSE: 0.8737 | val (dense) RMSE: 0.9528
Epoch 20 | train RMSE: 0.8697 | val (dense) RMSE: 0.9535
Best dense-val RMSE (NCF): 0.9510025550069597

In [41]:
def ncf_score(u, i):
    ncf_model.eval()
    g = int(user_gender[u])
    a = int(user_age[u])
    o = int(user_occupation[u])

    with torch.no_grad():
        u_t = torch.tensor([u], dtype=torch.long, device=device)
        i_t = torch.tensor([i], dtype=torch.long, device=device)
        g_t = torch.tensor([g], dtype=torch.long, device=device)
        a_t = torch.tensor([a], dtype=torch.long, device=device)
        o_t = torch.tensor([o], dtype=torch.long, device=device)

        pred = ncf_model(u_t, i_t, g_t, a_t, o_t).item()

    return float(pred)

In [42]:
# print("=== NCF ===")
# print("Dense:", rmse_for_scorer(val_dense_triplets, ncf_score))
# print("Cold :", rmse_for_scorer(cold_triplets, ncf_score))
# print("All  :", rmse_for_scorer(all_test_triplets, ncf_score))

In [43]:
print("\n================ FINAL MODEL COMPARISON ================\n")

recommenders = [
    ("Hybrid (SVD + CBF)", hybrid_score),
    ("NCF", ncf_score),
]

header = f"{'Model':30} {'RMSE dense':>10} {'RMSE cold':>10} {'RMSE all':>10}"
print(header)
print("-" * len(header))

for name, fn in recommenders:
    rmse_dense = rmse_for_scorer(test_dense_triplets, fn)
    rmse_cold = rmse_for_scorer(cold_triplets, fn)
    rmse_all = rmse_for_scorer(all_test_triplets, fn)
    print(f"{name:30} {rmse_dense:10.4f} {rmse_cold:10.4f} {rmse_all:10.4f}")

print("\n========================================================\n")

================ FINAL MODEL COMPARISON ================

Model                          RMSE dense  RMSE cold   RMSE all
---------------------------------------------------------------
Hybrid (SVD + CBF)                 0.9927     1.0218     1.0068
NCF                                0.9503     1.0404     0.9947

========================================================

In [44]:
def serendipity_for_scorer(triplets, score_fn, top_k=10, rel_thresh=4.0):
    # if you *already* have user_ratings, just pass it instead:
    user_ratings = build_user_ratings(triplets)

    user_ser = []
    for u in user_ratings.keys():
        s_u = serendipity_for_user(u, user_ratings, score_fn, top_k, rel_thresh)
        if s_u is not None:
            user_ser.append(s_u)

    if not user_ser:
        return 0.0

    return sum(user_ser) / len(user_ser)

In [45]:
print("\n=== Serendipity (Top-10, rel>=4.0) ===")
for name, fn in [
    ("Hybrid", hybrid_score),
    ("NCF", ncf_score),
]:

    s_dense = serendipity_for_scorer(test_dense_triplets, fn)
    s_cold = serendipity_for_scorer(cold_triplets, fn)
    s_all = serendipity_for_scorer(all_test_triplets, fn)
    print(
        f"{name} -> Serendipity dense: {s_dense:.4f} | "
        f"cold: {s_cold:.4f} | all: {s_all:.4f}"
    )

=== Serendipity (Top-10, rel>=4.0) ===
Hybrid -> Serendipity dense: 0.5324 | cold: 0.0000 | all: 0.5324
NCF -> Serendipity dense: 0.5410 | cold: 0.0000 | all: 0.5410